modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    authors = "${mod_author}"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "cloth_config"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[accessTransformers]]
    file="accesstransformers/1.21.1.cfg"